name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Intro
        run: |
          echo "Intro to Release"
          which python
          python --version
          which pip
          pip --version
      - name: Checkout Code
        uses: actions/checkout@v2
      - run: ls -aRl
      # - name: Installing dependencies
      #   run: 
      - name: Packaging the python applications


